Repository plentymarkets/plugin-ceres, pull requests merged in 2019-10, with the labels that each got.

#1536 UPDATE optimize loading wizard
  src/Providers/TemplateServiceProvider.php
  src/Wizard/ShopWizard/Repositories/ShopWizardConfigRepository.php
  src/Wizard/ShopWizard/Services/DefaultSettingsService.php
  src/Wizard/ShopWizard/Services/ShopWizardService.php
Labels: beta required, early required

#1557 Sb categoryitem/item grid widget
  contentWidgets.json
  resources/images/widgets/item-grid.svg
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres/widgets/Category/_item-grid-widget.scss
  resources/scss/ceres/widgets/Helper/_widget-appearance.scss
  resources/scss/ceres/widgets/_widgets.scss
  resources/views/Widgets/Category/ItemGridWidget.json
  resources/views/Widgets/Category/ItemGridWidget.twig
  src/Widgets/Category/ItemGridWidget.php
Labels: translation required

#1576 Fix/fix translations
  resources/lang/de/Template.properties
  resources/lang/de/Widget.properties
  resources/lang/en/Template.properties
  resources/lang/en/Widget.properties
Labels: translation required

#1571 ADD config for category tree depth
  config.json
  resources/lang/de/Config.properties
  resources/lang/de/Wizard.properties
  resources/lang/en/Config.properties
  resources/lang/en/Wizard.properties
  src/Config/CeresHeaderConfig.php
  src/Contexts/GlobalContext.php
  src/Wizard/ShopWizard/Config/OnlineStoreConfig.php
  src/Wizard/ShopWizard/Mapping/OnlineStoreMapping.php
  src/Wizard/ShopWizard/Steps/Builder/OnlineStoreStep.php
Labels: translation required

#1578 Feature/cookie bar
  contentWidgets.json
  resources/css/ceres-legacy.scss
  resources/css/ceres.css
  resources/css/ceres.min.css
  resources/css/ceres.scss
  resources/js/dist/ceres.js
  resources/js/dist/ceres.js.map
  resources/js/dist/ceres.min.js
  resources/js/dist/ceres.min.js.map
  resources/js/src/app/components/pageDesign/CookieBar.js
  resources/js/src/app/components/pageDesign/PrivacySettings.js
  resources/js/src/app/index.js
  resources/js/src/app/store/index.js
  resources/js/src/app/store/modules/ConsentModule.js
  resources/lang/de/Template.properties
  resources/lang/de/Widget.properties
  resources/lang/en/Template.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres.scss
  resources/scss/ceres/components/_cookie-bar.scss
  resources/scss/ceres/widgets/Helper/_widget-appearance.scss
  resources/views/PageDesign/Components/CookieBar.twig
  resources/views/PageDesign/Components/PrivacySettings.twig
  resources/views/PageDesign/PageDesign.twig
  resources/views/PageDesign/Partials/Footer.twig
  resources/views/Widgets/Common/PrivacySettingsWidget.json
  resources/views/Widgets/Common/PrivacySettingsWidget.twig
  resources/views/Widgets/Footer/CookieBarWidget.json
  resources/views/Widgets/Footer/CookieBarWidget.twig
  resources/views/Widgets/WidgetComponents.twig
  src/Providers/TemplateServiceProvider.php
  src/Widgets/Common/PrivacySettingsWidget.php
  src/Widgets/Footer/CookieBarWidget.php
Labels: beta required, translation required
