Repository plentymarkets/plugin-ceres, pull requests merged in 2019-12, with the labels that each got.

#1728 separate Desktop / Tablet / Mobile column settings
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Widgets/Category/ItemGridWidget.json
  resources/views/Widgets/Category/ItemGridWidget.twig
Labels: testing in progress

#1737 ADD sb item search
  resources/lang/de/Config.properties
  resources/lang/en/Config.properties
  resources/views/Category/Item/CategoryItem.twig
  shopBuilder.json
  src/Contexts/CategoryContext.php
  src/Contexts/ItemSearchContext.php
  src/ShopBuilder/Handler/ShopBuilderSettingsHandler.php
Labels: testing in progress

#1745 Sb categoryitem/fix layout container
  resources/views/Widgets/Category/ToolbarWidget.twig
  resources/views/Widgets/Item/ItemImageWidget.twig
  resources/views/Widgets/MyAccount/OrderHistoryWidget.twig
Labels: testing in progress

#1760 Sb categoryitem/add settings background widget
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres.scss
  resources/scss/ceres/common/_background.scss
  resources/scss/ceres/widgets/Common/_background-widget.scss
  resources/scss/ceres/widgets/Helper/_base-widget.scss
  resources/scss/ceres/widgets/_widgets.scss
  resources/views/Widgets/Common/BackgroundWidget.twig
  src/Widgets/Common/BackgroundWidget.php
Labels: testing in progress, translation required

#1774 BackgroundWidget - add placeholder; reduce colors in _background.scss; add custom color
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres.scss
  resources/scss/ceres/common/_background.scss
  resources/views/Widgets/Common/BackgroundWidget.twig
  resources/views/Widgets/Helper/WidgetHelper.twig
  src/Widgets/Common/BackgroundWidget.php
  src/Widgets/Helper/Factories/Settings/ColorPaletteSettingFactory.php
  src/Widgets/Helper/Factories/Settings/HeightSettingFactory.php
Labels: testing in progress

#1779 Refactor widget settings
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Widgets/Common/BackgroundWidget.twig
  src/Widgets/Common/BackgroundWidget.php
  src/Widgets/Helper/Factories/Settings/ColorPaletteSettingFactory.php
Labels: testing in progress

#1781 ADD lazy loading to ItemImageCaousel and BasketListItem
  resources/scss/ceres/plugins/_owl-carousel.scss
  resources/views/Basket/Components/BasketListItem.twig
  resources/views/Item/Components/ItemImageCarousel.twig
Labels: testing in progress

#1775 ADD dummy search string for item search in sb view
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  src/Widgets/Presets/DefaultItemSearchPreset.php
Labels: testing in progress

#1749 FIX guest login
  resources/js/src/app/components/customer/login/GuestLogin.js
  resources/views/Customer/Components/LoginView.twig
  resources/views/Widgets/Login/GuestLoginWidget.twig
  resources/views/Widgets/Login/LoginWidget.twig
Labels: testing in progress

#1796 Sb categoryitem/remove stepbystep
  resources/images/widgets/step-by-step-navigation.svg
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Widgets/Navigation/StepByStepNavigationWidget.twig
  src/Widgets/Navigation/StepByStepNavigationWidget.php
  src/Widgets/WidgetCollection.php
Labels: testing in progress

#1758 FIX improve detection of currently used template
  resources/js/src/app/services/ApiService.js
  resources/views/PageDesign/PageDesign.twig
  src/Contexts/GlobalContext.php
Labels: blocked

#1799 UPDATE dependencies
  package-lock.json
  package.json
Labels: testing in progress
