Repository plentymarkets/plugin-ceres, pull requests merged in 2019-11, with the labels that each got.

#1596 - Add dataFieldUnitsContentUnit for Unit
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/ResultFields/SingleItem.fields.json
  src/ShopBuilder/DataFieldProvider/Item/UnitDataFieldProvider.php
Labels: fix

#1598 Pagination Widget
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres/widgets/Helper/_widget-appearance.scss
  resources/views/Category/Item/CategoryItem.twig
  resources/views/Category/Item/Partials/Pagination.twig
  resources/views/MyAccount/Components/OrderHistory.twig
  resources/views/PageDesign/PageDesign.twig
  resources/views/Widgets/Category/PaginationWidget.json
  resources/views/Widgets/Category/PaginationWidget.twig
  src/Widgets/Category/PaginationWidget.php
Labels: translation required

#1583 Merge pull request #1582 from plentymarkets/feature/cookie_bar
  config.json
  contentWidgets.json
  resources/css/ceres-legacy.scss
  resources/css/ceres.css
  resources/css/ceres.min.css
  resources/css/ceres.scss
  resources/images/widgets/cookie-bar.svg
  resources/images/widgets/privacy-settings.svg
  resources/js/dist/ceres.js
  resources/js/dist/ceres.js.map
  resources/js/dist/ceres.min.js
  resources/js/dist/ceres.min.js.map
  resources/js/src/app/components/pageDesign/CookieBar.js
  resources/js/src/app/components/pageDesign/PrivacySettings.js
  resources/js/src/app/index.js
  resources/js/src/app/store/index.js
  resources/js/src/app/store/modules/ConsentModule.js
  resources/lang/de/Config.properties
  resources/lang/de/Template.properties
  resources/lang/de/Widget.properties
  resources/lang/de/Wizard.properties
  resources/lang/en/Config.properties
  resources/lang/en/Template.properties
  resources/lang/en/Widget.properties
  resources/lang/en/Wizard.properties
  resources/scss/ceres.scss
  resources/scss/ceres/components/_cookie-bar.scss
  resources/views/PageDesign/Components/CookieBar.twig
  resources/views/PageDesign/Components/PrivacySettings.twig
  resources/views/PageDesign/PageDesign.twig
  resources/views/Widgets/Common/PrivacySettingsWidget.json
  resources/views/Widgets/Common/PrivacySettingsWidget.twig
  resources/views/Widgets/Footer/CookieBarWidget.json
  resources/views/Widgets/Footer/CookieBarWidget.twig
  resources/views/Widgets/WidgetComponents.twig
  src/Config/CeresGlobalConfig.php
  src/Providers/TemplateServiceProvider.php
  src/Widgets/Common/PrivacySettingsWidget.php
  src/Widgets/Footer/CookieBarWidget.php
  src/Wizard/ShopWizard/Mapping/OnlineStoreMapping.php
  src/Wizard/ShopWizard/Steps/Builder/OnlineStoreStep.php
Labels: blocked

#1612 Sb categoryitem/item dynamic filter widget
  contentWidgets.json
  resources/js/src/app/components/itemList/filter/ItemFilter.js
  resources/js/src/app/components/itemList/filter/ItemFilterList.js
  resources/js/src/app/store/modules/ItemListModule.js
  resources/lang/de/Template.properties
  resources/lang/de/Widget.properties
  resources/lang/en/Template.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres/views/Category/_category-list-controls.scss
  resources/scss/ceres/widgets/Category/_item-dynamic-filter-widget.scss
  resources/scss/ceres/widgets/Category/_toolbar-widget.scss
  resources/scss/ceres/widgets/_widgets.scss
  resources/views/Category/Item/CategoryItem.twig
  resources/views/ItemList/Components/Filter/ItemFilter.twig
  resources/views/ItemList/Components/Filter/ItemFilterList.twig
  resources/views/ItemList/Components/Filter/ItemFilterListBulk.twig
  resources/views/Widgets/Category/ItemDynamicFilterWidget.json
  resources/views/Widgets/Category/ItemDynamicFilterWidget.twig
  resources/views/Widgets/Category/ToolbarWidget.json
  resources/views/Widgets/Category/ToolbarWidget.twig
  resources/views/Widgets/WidgetComponents.twig
  src/Widgets/Category/ItemDynamicFilterWidget.php
Labels: translation required, work in progress

#1625 UrlService - remove usage of the category url to build the target url
  resources/js/src/app/services/UrlService.js
Labels: work in progress

#1635 Block google maps since user accepts usage
  resources/js/src/app/components/common/GoogleMaps.js
  resources/js/src/app/helper/whenConsented.js
  resources/js/src/app/store/modules/ConsentModule.js
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/views/Widgets/Common/GoogleMapsWidget.twig
Labels: translation required

#1630 add property type file
  resources/js/src/app/filters/propertyFileUrl.filter.js
  resources/js/src/app/index.js
  resources/views/Basket/Components/BasketListItem.twig
  resources/views/PageDesign/PageDesign.twig
  src/Extensions/TwigItemDataField.php
  src/ShopBuilder/DataFieldProvider/Item/PropertyDataFieldProvider.php
  src/ShopBuilder/DataFieldProvider/Item/PropertyGroupDataFieldProvider.php
Labels: early required
