Repository plentymarkets/plugin-ceres, pull requests merged in 2019-07, with the labels that each got.

#1230 sb_single_item/ item_bundle_placeholder
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Item/Components/ItemBundle.twig
  resources/views/Widgets/Item/ItemBundleWidget.twig
Labels: translation required

#1264 SingleItem - Fallback for Artikelvorlage with empty template
  resources/views/Item/SingleItemWrapper.twig
Labels: fix

#1270 sb_legal_pages/legal_text_widget_placeholder
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres/widgets/Checkout/_shipping-privacy-check.scss
  resources/scss/ceres/widgets/Common/_item-list-widget.scss
  resources/scss/ceres/widgets/Common/_live-shopping-widget.scss
  resources/scss/ceres/widgets/_widgets.scss
  resources/views/Widgets/Checkout/ShippingPrivacyCheckWidget.twig
  resources/views/Widgets/Common/ItemListWidget.twig
  resources/views/Widgets/Common/LiveShoppingWidget.twig
  resources/views/Widgets/Legal/LegalTextsWidget.twig
Labels: translation required

#1275 VariationSelect - items without attributes, but with different units display the variation select now properly
  resources/js/src/app/components/item/SingleItem.js
  resources/js/src/app/components/item/VariationSelect.js
  resources/views/Item/Components/SingleItem/SingleItem_Details.twig
  resources/views/Item/Components/VariationSelect.twig
Labels: fix

#1279 VariationSelect - hide message "content is not available", if no initial variation was found
  resources/js/src/app/components/item/VariationSelect.js
  resources/js/src/app/store/modules/VariationSelectModule.js
Labels: fix

#1282 Fix/image widget box caption block mobile
  resources/scss/ceres/widgets/Common/_image-box-widget.scss
Labels: fix

#1280 Fix/title bar duplicate h1
  src/Widgets/Common/TitleBarWidget.php
Labels: fix

#1294 Feature/form widgets
  contentWidgets.json
  resources/css/ceres-legacy.scss
  resources/css/ceres.css
  resources/css/ceres.css.map
  resources/css/ceres.min.css
  resources/css/ceres.min.css.map
  resources/css/ceres.scss
  resources/images/widgets/contact-card.svg
  resources/images/widgets/input-mail.svg
  resources/images/widgets/input-select.svg
  resources/images/widgets/input-text.svg
  resources/images/widgets/input-textarea.svg
  resources/images/widgets/mail-form.svg
  resources/images/widgets/recaptcha.svg
  resources/js/dist/ceres-app.js
  resources/js/dist/ceres-app.js.map
  resources/js/dist/ceres.js
  resources/js/dist/ceres.min.js
  resources/js/dist/ceres.min.js.map
  resources/js/src/app/helper/serializeForm.js
  resources/js/src/app/helper/strings.js
  resources/js/src/app/services/ValidationService.js
  resources/js/src/app/store/index.js
  resources/js/src/app/store/modules/ContactForm.js
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres/forms/_inputs.scss
  resources/views/Customer/Components/Contact/ContactForm.twig
  resources/views/Customer/Components/Contact/ContactMail.twig
  resources/views/Widgets/Form/MailFormWidget.json
  resources/views/Widgets/Form/MailFormWidget.twig
  resources/views/Widgets/Form/MailInputWidget.json
  resources/views/Widgets/Form/MailInputWidget.twig
  resources/views/Widgets/Form/SelectionWidget.json
  resources/views/Widgets/Form/SelectionWidget.twig
  resources/views/Widgets/Form/TextAreaWidget.json
  resources/views/Widgets/Form/TextAreaWidget.twig
  resources/views/Widgets/Form/TextInputWidget.json
  resources/views/Widgets/Form/TextInputWidget.twig
  shopBuilder.json
  src/Providers/TemplateServiceProvider.php
  src/Widgets/Form/MailFormWidget.php
  src/Widgets/Form/MailInputWidget.php
  src/Widgets/Form/SelectionWidget.php
  src/Widgets/Form/TextAreaWidget.php
  src/Widgets/Form/TextInputWidget.php
Labels: translation required

#1319 Fix/sticky widget 4.1
  contentWidgets.json
  resources/js/src/app/helper/StickyElement.js
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Item/Components/SingleItem.twig
  resources/views/PageDesign/PageDesign.twig
  resources/views/PageDesign/Partials/Header/Header.twig
  resources/views/Widgets/Grid/StickyContainerWidget.json
  resources/views/Widgets/Grid/StickyContainerWidget.twig
  src/Widgets/Presets/DefaultSingleItemPreset.php
Labels: fix, translation required

#1322 Feature/add fade effect option to image carousel
  contentWidgets.json
  resources/js/src/app/components/item/ItemImageCarousel.js
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Widgets/Common/ImageCarouselWidget.json
  resources/views/Widgets/Common/ImageCarouselWidget.twig
  resources/views/Widgets/Item/ItemImageWidget.json
  resources/views/Widgets/Item/ItemImageWidget.twig
Labels: translation required
