Repository plentymarkets/plugin-ceres, pull requests merged in 2020-12, with the labels that each got.

#2536 FIX/add error handling for post to large exception
  resources/js/src/app/components/item/OrderPropertyListItem.vue
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
Labels: beta required

#2552 Feature/cypress basket
  package-lock.json
  package.json
  testing/cypress/integration/basket/basket.spec.js
  testing/cypress/integration/basket/coupon.spec.js
  testing/cypress/integration/checkout/payment-provider.spec.js
  testing/cypress/integration/contact/contact.spec.js
Labels: testing in progress

#2562 Feature/cypress default registration
  testing/cypress/integration/registration/default-registration.spec.js
Labels: testing in progress

#2554 add alt text to background widget
  resources/views/Widgets/Common/BackgroundWidget.twig
Labels: testing in progress

#2560 UPDATE payment test check vuex state
  testing/cypress/integration/checkout/payment-provider.spec.js
Labels: testing in progress

#2564 add a multilang key
  resources/js/src/app/components/basket/BasketTotals.vue
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
Labels: testing in progress

#2576 FIX lightbox label not translated
  resources/js/dist/chunks/ceres-32.js
  resources/js/dist/chunks/ceres-32.js.map
  resources/js/dist/chunks/ceres-32.min.js
  resources/js/dist/chunks/ceres-32.min.js.map
  resources/js/src/app/components/item/ItemImageCarousel.vue
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
Labels: translation required
