Repository plentymarkets/plugin-ceres, pull requests merged in 2020-04, with the labels that each got.

#2107 Feature/Item sets/preset
  resources/js/src/app/components/item/ItemImageCarousel.vue
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  shopBuilder.json
  src/Widgets/Presets/ItemSetPreset.php
Labels: testing in progress

#2109 FIX consider rebate in category item
  resources/js/src/app/components/itemList/CategoryItem.vue
Labels: testing in progress

#2118 Fix/default category pagination dublicate row
  resources/views/Category/Item/CategoryItem.twig
Labels: testing in progress

#2092 use new field for hasChildren condition
  resources/js/src/app/components/itemList/CategoryItem.vue
Labels: beta required

#2126 QuantityInput - the min / max values are now set correct
  resources/js/src/app/components/basket/AddItemToBasketOverlay.vue
  resources/js/src/app/components/basket/AddToBasket.vue
  resources/js/src/app/components/item/QuantityInput.vue
  resources/js/src/app/store/modules/BasketModule.js
Labels: testing in progress

#2135 Delete outdated buildfiles
  resources/css/ceres-category.scss
  resources/css/ceres-item.scss
  resources/js/dist/ceres-category.js
  resources/js/dist/ceres-category.js.map
  resources/js/dist/ceres-category.min.js
  resources/js/dist/ceres-category.min.js.map
  resources/js/dist/ceres-item.js
  resources/js/dist/ceres-item.js.map
  resources/js/dist/ceres-item.min.js
  resources/js/dist/ceres-item.min.js.map
Labels: testing in progress

#2144 Fix/category image carousel arrows
  config.json
  resources/lang/de/Config.properties
  resources/lang/en/Config.properties
  resources/scss/ceres/plugins/_owl-carousel.scss
  resources/scss/ceres/views/Templates/CategoryListItem/_category-list-item.scss
Labels: testing in progress, translation required

#2143 Remove storeName from assistant
  resources/lang/de/Wizard.properties
  resources/lang/en/Wizard.properties
  src/Wizard/ShopWizard/Mapping/OnlineStoreMapping.php
  src/Wizard/ShopWizard/Steps/Builder/OnlineStoreStep.php
Labels: testing in progress

#2130 Fix IE11 OrderPropertyListItem & property resetting of other set items
  resources/js/src/app/components/item/OrderPropertyListItem.vue
  resources/js/src/app/components/item/VariationSelect.vue
Labels: testing in progress

#2145 fix position of attributes in oder confirmation widget and order history
  resources/views/MyAccount/Partials/OrderHistoryListItemDetails.twig
  resources/views/Widgets/OrderConfirmation/PurchasedItemsWidget.twig
Labels: testing in progress

#2136 Remove properties from result fields for list items
  resources/views/ResultFields/ListItem.fields.json
Labels: testing in progress

#2131 Fix/order properties - match design (basket and overlay)
  resources/js/src/app/components/basket/AddItemToBasketOverlay.vue
  resources/js/src/app/filters/propertySurchargeSum.filter.js
  resources/js/src/base.js
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
Labels: testing in progress

#2087 ADD removal of content links for default homepage on plugin build
  src/Hooks/CeresAfterBuildPlugins.php
Labels: early required

#2146 ItemImageCarousel - fix lightbox issues with clones items
  resources/js/src/app/components/item/ItemImageCarousel.vue
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
Labels: update guide germane

#2139 use correct value
  resources/js/src/app/components/itemList/CategoryItem.vue
  resources/scss/ceres/views/Templates/CategoryListItem/_category-list-item.scss
Labels: work in progress

#2152 Feature/sales coupon
  resources/js/src/app/components/myAccount/EditCouponOverlay.vue
  resources/js/src/checkout.js
  resources/lang/de/Template.properties
  resources/scss/ceres/common/_buttons.scss
  resources/scss/ceres/common/_common.scss
  resources/scss/ceres/common/_modal.scss
  resources/scss/ceres/common/_reboot.scss
  resources/views/Widgets/OrderConfirmation/PurchasedItemsWidget.twig
Labels: testing in progress

#2137 remove prop and use computed value
  resources/js/src/app/components/itemList/CategoryItem.vue
  resources/views/PageDesign/PageDesign.twig
  resources/views/Widgets/Category/ItemGridWidget.twig
Labels: testing in progress

#2167 Calculate header after font is loaded
  resources/js/src/app/main.js
  resources/views/PageDesign/Partials/Head.twig
Labels: testing in progress

#2164 FIX carousel - owl carousel initialization
  resources/js/src/app/components/containers/LastSeenItemList.vue
  resources/js/src/app/components/pageDesign/Carousel.vue
Labels: testing in progress

#2171 fix/header_elements_overflow_safari
  resources/views/PageDesign/Partials/Header/DefaultHeader.twig
  resources/views/Widgets/Header/TopBarWidget.twig
Labels: testing in progress

#2172 Fix/change spacings itemset preset
  src/Widgets/Presets/ItemSetPreset.php
Labels: testing in progress

#2165 add function to inherit outta sorting to inner sorting and add from p…
  config.json
  resources/js/src/app/components/itemList/CategoryItem.vue
  resources/lang/de/Config.properties
  resources/lang/de/Template.properties
  resources/lang/de/Wizard.properties
  resources/lang/en/Config.properties
  resources/lang/en/Template.properties
  resources/lang/en/Wizard.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
  resources/views/PageDesign/PageDesign.twig
  src/Config/CeresSortingConfig.php
  src/Providers/TemplateServiceProvider.php
  src/Wizard/ShopWizard/Config/PaginationConfig.php
  src/Wizard/ShopWizard/Mapping/PaginationMapping.php
  src/Wizard/ShopWizard/Steps/Builder/PaginationStep.php
Labels: translation required

#2154 Feature/sales coupon return
  resources/js/src/app/components/orderReturn/OrderReturnItem.vue
  resources/js/src/app/exceptions/ExceptionMap.js
  resources/js/src/app/store/modules/OrderReturnModule.js
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
Labels: translation required

#2174 Fix/footer features max width
  resources/scss/ceres/views/PageDesign/_footer.scss
Labels: testing in progress

#2184 fix/background_widget_modals_z_index
  resources/scss/ceres/widgets/Common/_background-widget.scss
Labels: testing in progress

#2181 Fix a reference error blocking parallel loading of google maps
  resources/js/src/app/components/common/GoogleMaps.vue
Labels: testing in progress

#2180 Enable options for dropdown when in myAccount
  resources/js/src/app/components/customer/AddressInputGroup.vue
Labels: testing in progress

#2201 fix/hide privacy policy button text on mobile
  resources/js/src/app/components/pageDesign/CookieBar.vue
Labels: testing in progress

#2208 FIX/added margin settings to widget
  resources/views/Widgets/Navigation/StepByStepNavigationWidget.twig
  src/Widgets/Navigation/StepByStepNavigationWidget.php
Labels: testing in progress

#2212 Fixed: Owl initialization
  resources/js/src/app/components/pageDesign/Carousel.vue
Labels: testing in progress

#2215 FIX/fixed layoutcontainer naming
  resources/views/Widgets/Header/TopBarWidget.twig
Labels: testing in progress

#2214 FIX non sb order return for guests
  resources/views/OrderReturn/OrderReturnView.twig
  src/Contexts/OrderReturnContext.php
Labels: testing in progress
