Repository plentymarkets/plugin-ceres, pull requests merged in 2020-03, with the labels that each got.

#2014 fix seo information
  resources/views/Category/Item/CategoryItem.twig
  resources/views/Item/SingleItemWrapper.twig
  resources/views/PageDesign/Partials/Head.twig
  resources/views/PageDesign/Partials/PageMetadata.twig
Labels: testing in progress

#2010 Feature/image sourcesets
  package-lock.json
  package.json
  resources/js/src/app/components/common/LazyImg.vue
  resources/js/src/app/components/item/ItemImageCarousel.vue
  resources/js/src/app/components/itemList/CategoryImageCarousel.vue
  resources/js/src/app/helper/featureDetect.js
  resources/js/src/app/main.js
  resources/js/src/app/plugins/lozad.js
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres/common/_common.scss
  resources/scss/ceres/plugins/_owl-carousel.scss
  resources/scss/ceres/widgets/Common/_image-box-widget.scss
  resources/views/PageDesign/PageDesign.twig
  resources/views/Widgets/Common/BackgroundWidget.twig
  resources/views/Widgets/Common/ImageBoxWidget.twig
  src/Widgets/Common/BackgroundWidget.php
  src/Widgets/Common/ImageBoxWidget.php
Labels: testing in progress

#2000 Fix Orderdetails - show variation properties / remove variationPropertiesService
  resources/js/src/app/components/basket/list/BasketListItem.vue
  resources/js/src/app/components/item/SingleItem.vue
  resources/js/src/app/components/wishList/WishListItem.vue
  resources/js/src/app/services/VariationPropertyService.js
  resources/views/Checkout/OrderDetails.twig
  resources/views/ResultFields/BasketItem.fields.json
  resources/views/ResultFields/SingleItem.fields.json
  resources/views/Widgets/OrderConfirmation/PurchasedItemsWidget.twig
Labels: early required

#2030 Feature/search suggestion additional information
  resources/js/src/app/components/itemList/SearchSuggestionItem.vue
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/ResultFields/AutoCompleteListItem.fields.json
  resources/views/Widgets/Header/SearchSuggestionWidget.twig
  src/Widgets/Header/Search/SearchSuggestionBaseWidget.php
  src/Widgets/Header/Search/SearchSuggestionCategoryWidget.php
  src/Widgets/Header/Search/SearchSuggestionItemWidget.php
Labels: testing in progress

#2017 FIX/ background widget repeat and grid behavior
  resources/scss/ceres/widgets/Common/_background-widget.scss
  resources/scss/ceres/widgets/Grid/_grid-widget.scss
  resources/scss/ceres/widgets/Helper/_base-widget.scss
  resources/views/Widgets/Common/BackgroundWidget.twig
Labels: testing in progress

#2024 Fix/filter widgets styling
  resources/js/src/app/components/itemList/filter/ItemFilter.vue
  resources/scss/ceres/views/Category/_category-list-controls.scss
  resources/scss/ceres/widgets/Category/_filter-base-widget.scss
  resources/scss/ceres/widgets/Category/_price-filter-widget.scss
  resources/views/Category/Macros/CategoryTree.twig
Labels: testing in progress

#2035 Fix/sticky_element_update_on_resize
  resources/js/src/app/helper/StickyElement.js
Labels: testing in progress

#2044 feature/beta/items_sets/ add new widgetTypes "setitem, setonly"
  shopBuilder.json
  src/Widgets/Helper/WidgetTypes.php
  src/Widgets/Item/AddToBasketWidget.php
  src/Widgets/Item/AttributeWidget.php
  src/Widgets/Item/GraduatedPriceWidget.php
  src/Widgets/Item/ItemBundleWidget.php
  src/Widgets/Item/ItemPriceWidget.php
Labels: testing in progress

#2052 Feature/add itemset widget
  resources/js/src/app/components/item/ItemSetComponent.vue
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Widgets/Item/ItemSetWidget.twig
  src/Contexts/SingleItemContext.php
  src/Widgets/Item/ItemSetWidget.php
  src/Widgets/WidgetCollection.php
Labels: translation required

#2055 FIX/ remove_col_xs_classes_stable
  resources/views/Customer/Components/AddressInputGroup/Locale/BillingAddressInputGroupDE.twig
  resources/views/Customer/Components/AddressInputGroup/Locale/BillingAddressInputGroupGB.twig
  resources/views/Customer/Components/AddressInputGroup/Locale/DHLPackingStationAddressInputGroupDE.twig
  resources/views/Customer/Components/AddressInputGroup/Locale/DeliveryAddressInputGroupDE.twig
  resources/views/Customer/Components/AddressInputGroup/Locale/DeliveryAddressInputGroupGB.twig
  resources/views/Homepage/DefaultHomepage.twig
  resources/views/Newsletter/Components/NewsletterInput.twig
  resources/views/Widgets/Common/NewsletterWidget.twig
Labels: testing in progress

#2054 Fix/remove col xs classes
  resources/js/src/app/components/customer/AddressInputGroup.vue
  resources/js/src/app/components/newsletter/NewsletterInput.vue
  resources/views/Homepage/DefaultHomepage.twig
  resources/views/Widgets/Common/NewsletterWidget.twig
Labels: testing in progress

#2016 ADD search suggestions
  resources/views/Widgets/ShopBuilderDataStore.twig
Labels: testing in progress

#2066 Add isSet check to canBeAddedToBasketFlag to definetly ensure showing…
  resources/js/src/app/components/basket/AddToBasket.vue
  resources/js/src/app/components/itemList/CategoryItem.vue
  resources/js/src/app/components/liveShopping/LiveShoppingItem.vue
  resources/js/src/app/components/wishList/WishListItem.vue
  resources/views/ResultFields/BasketItem.fields.json
Labels: testing in progress

#2069 ADD item search did you mean suggestions
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
  src/Contexts/ItemListContext.php
  src/Contexts/ItemSearchContext.php
  src/Widgets/Presets/ItemSearchPreset.php
Labels: testing in progress

#2058 Fix/order property variation change set fields
  resources/js/src/app/components/item/OrderPropertyListItem.vue
  resources/js/src/app/store/modules/SingleItemModule.js
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
Labels: testing in progress

#2068 Fix/prop classes on imagebox and imageslider widget
  resources/views/Widgets/Common/ImageBoxWidget.twig
  resources/views/Widgets/Common/ImageCarouselWidget.twig
Labels: testing in progress

#2079 Validate set components order properties
  resources/js/src/app/store/modules/singleItem/ItemModule.js
Labels: testing in progress

#2083 Display set price in category item
  resources/js/src/app/components/itemList/CategoryItem.vue
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
Labels: translation required

#2093 Add alignment setting to quantity input widget for better configuration
  resources/js/src/app/components/item/SetQuantityInput.vue
  resources/scss/ceres/views/Templates/Item/_quantity-input.scss
  resources/views/Widgets/Item/QuantityInputWidget.twig
  src/Widgets/Item/QuantityInputWidget.php
Labels: testing in progress

#2097 AddItemToBasketOverlay.vue - the prices of current set configuration is now shown in the overlay
  resources/js/src/app/components/basket/AddItemToBasketOverlay.vue
Labels: testing in progress

#2095 use new data source to correctly set min and max quantities and disab…
  resources/js/src/app/components/item/SetQuantityInput.vue
  resources/js/src/app/store/modules/singleItem/BaseItemModule.js
Labels: blocked

#2104 Use given set price to display while loading set - avoid zero price
  resources/js/src/app/components/item/SetPrice.vue
  resources/js/src/app/store/modules/singleItem/BaseItemModule.js
Labels: testing in progress
