Repository plentymarkets/plugin-ceres, pull requests merged in 2021-04, with the labels that each got.

#2763 ADD ssr toggle for assistant and config
  config.json
  resources/lang/de/Config.properties
  resources/lang/de/Wizard.properties
  resources/lang/en/Config.properties
  resources/lang/en/Wizard.properties
  src/Config/CeresLogConfig.php
  src/Providers/TemplateServiceProvider.php
  src/Wizard/ShopWizard/Mapping/PerformanceMapping.php
  src/Wizard/ShopWizard/Steps/Builder/PerformanceStep.php
Labels: translation required

#2783 Fix/tab widget aria role
  resources/js/src/app/components/common/TabList.vue
Labels: testing in progress

#2794 Feature/widget link title
  resources/js/src/app/directives/common/truncateTooltip.js
  resources/js/src/app/main.js
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Widgets/Common/LinkWidget.twig
  src/Widgets/Common/LinkWidget.php
Labels: translation required

#2807 Fix ssr autocomplete search
  resources/js/src/app/store/modules/ItemSearchModule.js
Labels: testing in progress

#2782 Check if there is at least one parcel preset with post office or parc…
  resources/js/src/app/components/customer/AddressInputGroup.vue
  resources/js/src/app/components/customer/AddressSelect/ShippingAddressSelect.js
  resources/views/MyAccount/MyAccountView.twig
  resources/views/Widgets/Customer/AddressWidget.twig
Labels: early required
