Repository plentymarkets/plugin-ceres, pull requests merged in 2021-02, with the labels that each got.

#2629 FIX/add aria labels for accessability
  resources/js/src/app/components/customer/login/UserLoginHandler.vue
  resources/js/src/app/components/itemList/ItemSearch.vue
  resources/js/src/app/components/pageDesign/ShippingCountrySelect.vue
  resources/js/src/app/components/wishList/WishListCount.vue
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
  resources/views/PageDesign/Partials/Header/DefaultHeader.twig
  resources/views/Widgets/Header/TopBarWidget.twig
Labels: testing in progress, translation required

#2622 children elements needs an option
  resources/js/src/app/components/itemList/CategoryImageCarousel.vue
  resources/js/src/app/components/pageDesign/CookieBar.vue
  resources/lang/de/Template.properties
  resources/lang/en/Template.properties
  resources/lang/fr/Template.properties
  resources/lang/nl/Template.properties
  resources/lang/pl/Template.properties
  resources/views/Widgets/Common/ImageCarouselWidget.twig
Labels: translation required

#2653 change autocomplete setting for honeypot to 'new-password'
  resources/js/src/app/components/customer/Registration.vue
  resources/js/src/app/components/customer/login/ForgotPassword.vue
  resources/js/src/app/components/newsletter/NewsletterUnsubscribeInput.vue
  resources/views/Customer/Contact.twig
  resources/views/Widgets/Form/MailFormWidget.twig
Labels: testing in progress

#2648 Fix/order property type float
  resources/js/src/app/components/item/OrderPropertyListItem.vue
Labels: testing in progress

#2687 FIX/use default values for normale menu settings
  resources/views/Widgets/Header/NavigationWidget.twig
Labels: testing in progress
