Repository plentymarkets/plugin-ceres, pull requests merged in 2021-05, with the labels that each got.

#2804 Feature/seo brand
  config.json
  resources/lang/de/Config.properties
  resources/lang/de/Wizard.properties
  resources/lang/en/Config.properties
  resources/lang/en/Wizard.properties
  resources/views/Item/SingleItemWrapper.twig
  src/Config/CeresConfig.php
  src/Config/CeresSeoConfig.php
  src/Contexts/SingleItemContext.php
  src/Wizard/ShopWizard/Config/SeoConfig.php
  src/Wizard/ShopWizard/Mapping/SeoMapping.php
  src/Wizard/ShopWizard/Steps/Builder/SeoStep.php
Labels: translation required

#2826 UPDATE shopbooster text
  resources/lang/de/Wizard.properties
  resources/lang/en/Wizard.properties
Labels: translation required

#2856 Feature/add option for imagebox to retain aspect ratio of image
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/scss/ceres/widgets/Common/_image-box-widget.scss
  resources/views/Widgets/Common/ImageBoxWidget.twig
  src/Widgets/Common/ImageBoxWidget.php
Labels: translation required

#2855 FIX/form_multiple_checkboxes_required
  resources/js/src/app/services/ValidationService.js
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Widgets/Form/SelectionWidget.twig
  src/Widgets/Form/SelectionWidget.php
Labels: translation required

#2862 Feature/preload itemlist
  resources/lang/de/Widget.properties
  resources/lang/en/Widget.properties
  resources/views/Widgets/Common/ItemListWidget.twig
  src/Widgets/Common/ItemListWidget.php
Labels: testing in progress

#2867 ADD option for session lifetime of one day
  resources/lang/de/Wizard.properties
  resources/lang/en/Wizard.properties
  src/Wizard/ShopWizard/Config/OnlineStoreConfig.php
Labels: early required
